// <auto-generated />
using LibreLms.Modules.Catalog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Host.Migrations.Catalog
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20260805020000_AddFullTextIndexAndBrowseProcedure")]
    partial class AddFullTextIndexAndBrowseProcedure
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreLms.Modules.Catalog.Domain.Course", b =>
            {
                b.Property<System.Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<System.DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Duration")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<string>("FullDescription")
                    .IsRequired()
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<System.Guid>("OrganizationId")
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("ShortDescription")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("Title", "OrganizationId")
                    .IsUnique();

                b.ToTable("Courses");
            });
        }
    }
}
